### ISSUE TITLE
Support for Windows 7/8 x64

### ISSUE THREAD

**Issue by ksmohan** [nathanjohnson320/run-command2#1]
There are some cases where such a functionality is useful even in Windows.  Since this package explicitly states that it can run only Unix commands, it does not work for Windows OSs.

**Comment by nathanjohnson320** [comment]
I added basic support for windows. Let me know if it works!

**Comment by ksmohan** [comment]
The command that I need to run on the windows command line works. But things like "set working directory" does not seem to work. But this will work fine for now. Thank you for the quick fix.
