### ISSUE TITLE
Auto-scroll terminal pane?

### ISSUE THREAD

**Issue by obibring** [nathanjohnson320/run-command2#4]
I'm using your fabulous plugin to run tests. When I do so, test results are printed below the fold of the terminal pane. Consequently, I must manually scroll the terminal pane downwards to see the test results. It'd be nice if the pane would auto-scroll as content is printed, just like in a normal shell.

Any possibility to support this?

**Comment by nathanjohnson320** [comment]
Yeah shouldn't be too hard to fix :)

**Comment by nathanjohnson320** [comment]
Should be fixed now, there's a config option that enables scroll to bottom it's set to true by default but after I fixed some deprecations it broke.

**Comment by obibring** [comment]
Thanks!
